<?php

use Drupal\beam_misc\Helper\CookieHelper;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function beam_order_theme($existing, $type, $theme, $path) {
  return [
    'beam_order' => [
      'path' => $path . '/templates',
      'template'  => 'beam_order',
      'render element' => 'content',          // Theme API call to define the container of the entity in the render array
    ],
    'beam_order_comment' => [
      'variables' => [
        'date' => NULL,
        'user' => NULL,
        'body' => ''
      ]
    ],
  ];
}
